/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host"
#define EXEC_PREFIX "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host"
#define BINDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/bin"
#define SBINDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/bin"
#define LIBEXECDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/libexec"
#define DATAROOTDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share"
#define DATADIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share"
#define SYSCONFDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/etc"
#define SHAREDSTATEDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/com"
#define LOCALSTATEDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/var"
#define RUNSTATEDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/var/run"
#define INCLUDEDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/doc/bison"
#define INFODIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/info"
#define HTMLDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/doc/bison"
#define DVIDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/doc/bison"
#define PDFDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/doc/bison"
#define PSDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/doc/bison"
#define LIBDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/lib"
#define LISPDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/emacs/site-lisp"
#define LOCALEDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/locale"
#define MANDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/man"
#define PKGDATADIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/share/bison"
#define PKGINCLUDEDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/include/bison"
#define PKGLIBDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/lib/bison"
#define PKGLIBEXECDIR "/mnt/sdb/THG6500-MINI-TAX2-OPENWRT-BSP_TGP3/staging_dir/host/libexec/bison"
